// @ez2bms/chart-core - public surface. Everything here is pure TypeScript with
// no DOM and no Tauri: it runs the same in the editor, in Vitest and in Node.
export const CHART_CORE_VERSION = '0.1.0';

export * from './model/types';
export * from './model/defaults';
export * from './modes/ids';
export * from './io/text';
export * from './io/bmson/parse';
export * from './io/bmson/serialize';
export * from './io/bmson/mode-resolve';
export * from './io/bmson/legacy-remap';
export { stableStringify, JsonValueError } from './util/stable-json';
export * from './timing/timing-map';
export * from './timing/ticks';
export * from './timing/engine-tempo';
export * from './timing/measures';
export * from './timing/snap';
export * from './timing/rescale';
export * from './io/ez/ezff';
export { lowerBound, upperBound } from './util/sorted';
export * from './modes/lanes';
export * from './modes/registry';
export * from './modes/layout';
export * from './modes/filenames';
export * from './ez2data/gds';
export * from './ez2data/pvi';
export * from './ez2data/abm';
export * from './ez2data/crypt';
export * from './ez2data/keytable';
export * from './ez2data/mixparam';
export { decodeCp949 } from './ez2data/initext';
export * from './edit/note-index';
export * from './edit/doc';
export * from './edit/commands';
export * from './publish/keysounds';
export * from './publish/tracks';
export * from './publish/chart-plan';
export * from './publish/playback';
export * from './publish/audible';
export * from './publish/text';
export * from './publish/package';
export * from './engine/songini';
export * from './engine/score';
export * from './engine/session';
export * from './engine/judge-sim';
export * from './lint/lint';
export * from './sound/resolve';
export * from './sound/grouping';
export * from './sound/usage';
export { synthChart, synthDoc, type SynthOptions } from './dev/synth';
